# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-builder" do
  name "agent-builder"
  desc "ADK Multi-Agent Builder CLI"
  homepage "https://github.com/doji-co/agent-builder"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-builder"

  on_macos do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_x86_64.tar.gz"
      sha256 "062a9c9044b9a7d6942fedecdaff0df71425536c8067a27b46fb4f869cd3c864"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_arm64.tar.gz"
      sha256 "26f53a5d5c824b83fced3c795e4de758214d1b866d10513f13e308ff561b5093"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_x86_64.tar.gz"
      sha256 "81e71ce152269278386adcc6fb16a0df0c671db0d06fa1f3f217a1993b00a1c7"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_arm64.tar.gz"
      sha256 "6cc9bdcfe5b44b4563ca258c5e9e5ed8f214ae100554985e91c96cd26a8af860"
    end
  end

  # No zap stanza required
end
