# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-builder" do
  name "agent-builder"
  desc "ADK Multi-Agent Builder CLI"
  homepage "https://github.com/doji-co/agent-builder"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-builder"

  on_macos do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_x86_64.tar.gz"
      sha256 "6c05887509559885aa2569ec837f98a20b1b6f38bf0386d06d8c0055214769e5"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_arm64.tar.gz"
      sha256 "cb7573c287472508a9b1ef26ee881557be072001d1e3352de2305f29fc6ddcd4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_x86_64.tar.gz"
      sha256 "c6ef43e2c5dbdb223ed9921bd0b57266c852a6dff63eea9e9bf5c6e632f9d3e1"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_arm64.tar.gz"
      sha256 "a6f081e9a705623b6da170b464f32d722bf190bc1567a768e607a0926c3f1f7c"
    end
  end

  # No zap stanza required
end
