# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-builder" do
  name "agent-builder"
  desc "ADK Multi-Agent Builder CLI"
  homepage "https://github.com/doji-co/agent-builder"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-builder"

  on_macos do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_x86_64.tar.gz"
      sha256 "46d2acad8edd9c53d733494e290afcd5b15d79345879182eff5059a675ea84b4"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Darwin_arm64.tar.gz"
      sha256 "305c4938a6b4fe1827aad1fa5303674e976f74b6884dc635f832b6438240e774"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_x86_64.tar.gz"
      sha256 "7b76a00a9ea72937b5863e4c4344887f1e7fd5720ba996d822cd5e0656148b3a"
    end
    on_arm do
      url "https://github.com/doji-co/agent-builder/releases/download/v#{version}/agent-builder_Linux_arm64.tar.gz"
      sha256 "f25c4742df89ff5766f919c1ab8fbbfc048e2ce1df4742e4d4ba11dba421977a"
    end
  end

  # No zap stanza required
end
